### PR TITLE
Fixed interpretation of (Right False) in rsa/dsa verification.

### PR DESCRIPTION
**Pull request by joecrayne**
I tried to validate a signed UserID packet after modifying it's content.  To my surprise, it validated.  Upon inspe
cting the code, it seems that verifyOne is blowing away the negative results of validation, which Crypto.Cipher.RSA
 returns as Right False.

### CODE REVIEW

**Comment by singpolyma** [comment]
Oh, man.  That's a bad one.  Can you add a test case as well, to make sure failing happens?  I guess my tests in the past have been on signatures that failed instead of not validating or something...

**Comment by joecrayne** [comment]
I'll see what i can do.

**Comment by joecrayne** [comment]
Okay, there's testVerifyModifiedMessage now that detects the failure.

**Comment by singpolyma** [comment]
I have cleaned up some formatting and merged this into master.

**Pull request closed without merging**
